spring:
  application:
    name: test
  jvm:
    options: "-Xms512m -Xmx2g"
  datasource:
    url: jdbc:mysql://localhost:3306/sys?allowLoadLocalInfile=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

logging:
  level:
    org:
      springframework:
        web: INFO
        jdbc:
          core: INFO
          #JdbcTemplate: DEBUG
#      hibernate:
#        SQL: DEBUG
#        type: DEBUG

